### ISSUE TITLE
The data is bin format, how can I use it ?

### ISSUE THREAD

**Issue by HelloCentaurus** [byeongkeun-kang/HandTracking#1]

**Comment by byeongkeun-kang** [comment]
**Here is an example of how to read the data:**

char fname[sizeof "input_00000.bin"];
sprintf(fname, "input_%05d.bin", numb);
int length;

char *memblock;
std::ifstream file(fname, std::ios::binary);
if (file.is_open())
{
    file.seekg(0, std::ios::end);
    length = (int) file.tellg();
    memblock = new char [length];
    file.seekg(0, std::ios::beg);
    file.read(memblock, length);
    f = (float *)memblock;
}
file.close();

**Then, the depth at each pixel can be accessed as follows:**

for (int y=0; y < img_height; y++) {
    for (int x=0; x < img_width; x++) {
        unsigned short d = (unsigned short)f[y*img_width+x];
    }
}
